entropydata.client.host=https://api.entropy-data.com
entropydata.client.apikey=your-api-key

entropydata.client.snowflake.account=<ORGANIZATION-ACCOUNT>
entropydata.client.snowflake.user=ENTROPYDATA_CONNECTOR
entropydata.client.snowflake.privatekeyfile=file:/rsa_key.p8

entropydata.client.snowflake.assets.enabled=true
entropydata.client.snowflake.assets.connectorid=snowflake-assets
entropydata.client.snowflake.assets.pollinterval=PT10M

entropydata.client.snowflake.accessmanagement.enabled=true
entropydata.client.snowflake.accessmanagement.connectorid=snowflake-access-management
